global:
  scrape_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: "backend"
    metrics_path: '/metrics'
    static_configs:
      - targets: [ "backend:8000" ]
      
  - job_name: "postgres"
    metrics_path: '/metrics'
    static_configs:
      - targets: [ "postgres-exporter:9187" ]
      
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']
    
  - job_name: "redis"
    metrics_path: '/metrics'
    static_configs:
      - targets: [ "redis-exporter:9121" ]